server:
  port: 8082
  servlet:
    context-path: /api


spring:
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: 127.0.0.1
    # 服务器连接端口
    port: 6379
    # 服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 18
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 0